### PR TITLE
Use the first person pronoun

### PR DESCRIPTION
**Pull request by maxjacobson**
No royal we :)

### CODE REVIEW

**Comment by conradkleinespel** [comment]
Wow, that was fast ! Thanks ! :+1:

**Comment by maxjacobson** [comment]
Heh my pleasure. I went to a http://novemb.rs/ meetup yesterday and dipped back into rust stuff 😄

**Comment by conradkleinespel** [comment]
@maxjacobson Nice ! What did you work on ? :smiley:

**Comment by maxjacobson** [comment]
Ah, mostly this. I did a few exercism.io problems as well. Very nice to have some people around to explain strings to me in person

**Comment by conradkleinespel** [comment]
@maxjacobson Sounds good ! I didn't know about exercism.io, I will be checking it out though. Thanks :smiley:

**Comment by maxjacobson** [comment]
Yea, they're pretty awesome. The very first problem was kind of tricky for me due to some ownership confusion, so it was cool to have someone around to walk me thru it. Here's an example solution http://exercism.io/submissions/77c38d1f0c4442ccbd2f8870ed1bba83

**Comment by conradkleinespel** [comment]
@maxjacobson ah yeah, lifetimes & ownership have bitten me quite a few times in the past as well with Rust ! Definitely a bit tough to grasp at first.

**Pull request merged**
